partes[0][uuid]=bf116136495b11ed87ab42010a2b6031
&partes[0][nome]=Lucas+Rubian+Schatz
&partes[0][email]=lucasschatz@gmail.com
&partes[0][cpf]=06288706981
&partes[0][nascimento]=1987-09-10
&partes[0][ordem]=0
&partes[0][assinatura][formato]=e
&partes[0][assinatura][imagem]=
&partes[0][funcao]=assinar
&partes[0][created]=2022-10-11+08:56:31
&partes[1][uuid]=bf14b521495b11ed87ab42010a2b6031
&partes[1][nome]=Lucas+Schatz
&partes[1][email]=schatz@srssistemas.com
&partes[1][cpf]=06288706981
&partes[1][nascimento]=1987-09-10
&partes[1][ordem]=1
&partes[1][assinatura][formato]=s
&partes[1][assinatura][imagem]=
&partes[1][funcao]=assinar
&partes[1][created]=2022-10-11+08:56:31
&partes[1][visualizado][created]=2022-10-11+08:57:05
&partes[1][visualizado][ipv4]=177.131.121.1
&partes[1][visualizado][geotrack][country]=Brazil
&partes[1][visualizado][geotrack][countryISO]=BR
&partes[1][visualizado][geotrack][state]=Santa+Catarina
&partes[1][visualizado][geotrack][stateISO]=SC
&partes[1][visualizado][geotrack][city]=Joaçaba
&partes[1][visualizado][geotrack][zipcode]=89600
&partes[1][visualizado][geotrack][latitude]=-27.1552
&partes[1][visualizado][geotrack][longitude]=-51.5902
&partes[1][assinado][created]=2022-10-11+08:57:23
&partes[1][assinado][ipv4]=177.131.121.1
&partes[1][assinado][geotrack][country]=Brazil
&partes[1][assinado][geotrack][countryISO]=BR
&partes[1][assinado][geotrack][state]=Santa+Catarina
&partes[1][assinado][geotrack][stateISO]=SC
&partes[1][assinado][geotrack][city]=Joaçaba
&partes[1][assinado][geotrack][zipcode]=89600
&partes[1][assinado][geotrack][latitude]=-27.1552
&partes[1][assinado][geotrack][longitude]=-51.5902
&partes[1][mail][sent]=2022-10-11+08:56:34
&partes[1][mail][delivered]=2022-10-11+08:56:48
&documento[uuid]=e8fd9ed520504a75756e74336328f1e8560355752eac012d5
&documento[nome]=Contrato+cliente+LRSeg+rev+2.docx
&documento[rejeitavel]=0
&documento[ordenavel]=0
&documento[created]=2022-10-11+08:56:29
&documento[updated]=2022-10-11+08:57:23
&documento[assinatura]=52e2e1c5b9842c41120fa02b0b6315e83d803a76
&documento[publicado]=2022-10-11+08:56:31
&documento[disponivel]=1
&organizacao=1
&remetente[nome]=Lucas+Rubian+Schatz
&remetente[email]=lucasschatz@gmail.com
&remetente[cpf]=06288706981
&remetente[nascimento]=1987-09-10
&arquivo[original]=https://storage.googleapis.com/d6e/d6cc69be787ce986135c7f9be1f1541f/haodg8IvoviVeRT2gEU7iluiQ9kvKKv5IcHRBQJV.original.pdf
&arquivo[assinado]=https://api.autentique.com.br/documentos/e8fd9ed520504a75756e74336328f1e8560355752eac012d5/assinado.pdf